
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/appscode/go"

[[constraint]]
  name = "github.com/appscode/jsonpatch"

[[constraint]]
  branch = "master"
  name = "github.com/appscode/searchlight"

[[constraint]]
  branch = "master"
  name = "github.com/appscode/stash"

[[constraint]]
  branch = "master"
  name = "github.com/appscode/voyager"

[[constraint]]
  name = "github.com/coreos/prometheus-operator"
  version = "0.12.0"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-version"
  source = "https://github.com/appscode/go-version.git"

[[constraint]]
  name = "github.com/k8sdb/apimachinery"
  branch = "mysqlDB"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "5fa44608f6b9b2180a2fd1ecb52e651fd0397794"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"

[[constraint]]
  name = "k8s.io/client-go"
  version = "4.0.0"

[[constraint]]
  branch = "release-branch.go1.8"
  name = "golang.org/x/net"
